name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
  update-build-badge:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: Extract the branch from the ref
      run: echo $(py ./GithubActions/branchExtractor.py ${{ github.ref }})
    - name: Update the build badge
      if: ${{ branch }} != ""
      run: echo $(py ./GitHubActions/badgeReplacer.py build ${{ github.repository }} ${{ branch }})
    - name: Push the update
      if: ${{ changedReadme }} == 1
      uses: ad-m/github-push-action@$branch
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
